package org.acme.recurring;

import java.util.List;

import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

import jakarta.inject.Inject;
import jakarta.validation.Valid;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.core.Response;

@Path("/recurring-transactions")
@Tag(name = "Recurring Transactions", description = "Manage recurring transaction templates (auto-generated by scheduler)")
public class RecurringTransactionResource {

    @Inject
    RecurringTransactionService recurringTransactionService;

    @GET
    @Operation(summary = "List all recurring transactions")
    public List<RecurringTransaction> list() {
        return recurringTransactionService.listAll();
    }

    @GET
    @Path("/{id}")
    @Operation(summary = "Get recurring transaction by ID")
    @APIResponse(responseCode = "404", description = "Recurring transaction not found")
    public RecurringTransaction get(@Parameter(description = "Recurring transaction ID") @PathParam("id") Long id) {
        return recurringTransactionService.findById(id);
    }

    @POST
    @Operation(summary = "Create a recurring transaction")
    @APIResponse(responseCode = "201", description = "Recurring transaction created")
    public Response create(@Valid RecurringTransaction rt) {
        RecurringTransaction created = recurringTransactionService.create(rt);
        return Response.status(Response.Status.CREATED).entity(created).build();
    }

    @PUT
    @Path("/{id}")
    @Operation(summary = "Update a recurring transaction")
    @APIResponse(responseCode = "404", description = "Recurring transaction not found")
    public RecurringTransaction update(@Parameter(description = "Recurring transaction ID") @PathParam("id") Long id, @Valid RecurringTransaction updated) {
        return recurringTransactionService.update(id, updated);
    }

    @DELETE
    @Path("/{id}")
    @Operation(summary = "Delete a recurring transaction")
    @APIResponse(responseCode = "204", description = "Recurring transaction deleted")
    public Response delete(@Parameter(description = "Recurring transaction ID") @PathParam("id") Long id) {
        recurringTransactionService.delete(id);
        return Response.noContent().build();
    }
}
