package org.acme.recurring;

import java.time.LocalDateTime;
import java.util.List;

import org.acme.account.Account;
import org.acme.category.Category;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.Response;

@Path("/recurring-transactions")
@Tag(name = "Recurring Transactions", description = "Manage recurring transaction templates (auto-generated by scheduler)")
public class RecurringTransactionResource {

    @GET
    @Operation(summary = "List all recurring transactions")
    public List<RecurringTransaction> list() {
        return RecurringTransaction.listAll();
    }

    @GET
    @Path("/{id}")
    @Operation(summary = "Get recurring transaction by ID")
    @APIResponse(responseCode = "404", description = "Recurring transaction not found")
    public RecurringTransaction get(@Parameter(description = "Recurring transaction ID") @PathParam("id") Long id) {
        RecurringTransaction rt = RecurringTransaction.findById(id);
        if (rt == null) {
            throw new WebApplicationException("Recurring transaction not found", 404);
        }
        return rt;
    }

    @POST
    @Transactional
    @Operation(summary = "Create a recurring transaction")
    @APIResponse(responseCode = "201", description = "Recurring transaction created")
    public Response create(@Valid RecurringTransaction rt) {
        if (rt.account != null && rt.account.id != null) {
            rt.account = Account.findById(rt.account.id);
        }
        if (rt.category != null && rt.category.id != null) {
            rt.category = Category.findById(rt.category.id);
        }
        rt.persist();
        return Response.status(Response.Status.CREATED).entity(rt).build();
    }

    @PUT
    @Path("/{id}")
    @Transactional
    @Operation(summary = "Update a recurring transaction")
    @APIResponse(responseCode = "404", description = "Recurring transaction not found")
    public RecurringTransaction update(@Parameter(description = "Recurring transaction ID") @PathParam("id") Long id, @Valid RecurringTransaction updated) {
        RecurringTransaction rt = RecurringTransaction.findById(id);
        if (rt == null) {
            throw new WebApplicationException("Recurring transaction not found", 404);
        }
        rt.amount = updated.amount;
        rt.description = updated.description;
        rt.frequency = updated.frequency;
        rt.nextDueDate = updated.nextDueDate;
        rt.endDate = updated.endDate;
        rt.active = updated.active;
        rt.type = updated.type;
        if (updated.account != null && updated.account.id != null) {
            rt.account = Account.findById(updated.account.id);
        }
        if (updated.category != null && updated.category.id != null) {
            rt.category = Category.findById(updated.category.id);
        }
        rt.updatedAt = LocalDateTime.now();
        return rt;
    }

    @DELETE
    @Path("/{id}")
    @Transactional
    @Operation(summary = "Delete a recurring transaction")
    @APIResponse(responseCode = "204", description = "Recurring transaction deleted")
    public Response delete(@Parameter(description = "Recurring transaction ID") @PathParam("id") Long id) {
        RecurringTransaction rt = RecurringTransaction.findById(id);
        if (rt == null) {
            throw new WebApplicationException("Recurring transaction not found", 404);
        }
        rt.delete();
        return Response.noContent().build();
    }
}
